# Generated by Django 5.1.2 on 2024-10-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
