# Generated by Django 5.1.2 on 2024-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0003_vendedores_correo_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
