# Generated by Django 5.1.2 on 2024-10-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0005_rename_vendedor_vendedores_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellidos', models.TextField(max_length=20)),
                ('direccion', models.TextField(max_length=20)),
                ('poblacion', models.TextField(max_length=20)),
                ('telefono', models.TextField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
