# Generated by Django 5.1.2 on 2024-10-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0006_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestordeventas.vendedores'),
        ),
    ]
