# Generated by Django 5.1.2 on 2024-10-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0007_clientes_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestordeventas.vendedores'),
        ),
    ]
