# Generated by Django 5.1.2 on 2024-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0008_alter_clientes_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.TextField(max_length=50),
        ),
    ]
