# Generated by Django 5.1.2 on 2024-10-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0010_ventas_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestordeventas.vendedores'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestordeventas.vendedores'),
        ),
    ]
