# Generated by Django 5.1.2 on 2024-10-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0011_alter_clientes_vendedor_alter_ventas_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestordeventas.vendedores'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestordeventas.articulos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestordeventas.clientes'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestordeventas.vendedores'),
        ),
    ]
