# Generated by Django 5.1.2 on 2024-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0013_ventas_total_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='precio_unitario',
            field=models.FloatField(null=True),
        ),
    ]
