# Generated by Django 5.1.2 on 2024-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0014_ventas_precio_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='precio_unitario',
            new_name='total_venta_c_iva',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='total_venta',
            new_name='total_venta_s_iva',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='precio',
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_c_iva',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_s_iva',
            field=models.FloatField(null=True),
        ),
    ]
