# Generated by Django 5.1.2 on 2024-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0016_alter_articulos_precio_c_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='poblacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
