# Generated by Django 5.1.2 on 2024-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0017_alter_clientes_apellidos_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
