# Generated by Django 5.1.2 on 2024-10-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestordeventas', '0019_alter_vendedores_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio_s_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
